#!/usr/bin/python3
from lxml import etree

# Parse our input generated by gpsbabel as an element tree
input_root = etree.parse("kmltest.kml").getroot()

kml_default_namespace="http://www.opengis.net/kml/2.2"

# Create an output document for us to write to
output_root = etree.Element("kml", nsmap={None: kml_default_namespace})

# Add in routes
routes_folder = etree.SubElement(output_root, "Folder")

routes_folder_name = etree.SubElement(routes_folder,"name")
routes_folder_name.text = "Walking Routes"


# The structure of the gpsbabel generated docuemnt is:
# Folder (name="Routes")
# 	Folder (name=**route_name1**)
#		Placemark (name="Path") [data is here]
# 	Folder (name=**route_name2**)
#		Placemark (name="Path") [data is here]

# Flatten this to:
# Folder (name="Walking Routes")
# 	Folder (name=**route_name1**)
#		Placemark (name="Path") [data is here]
# 	Folder (name=**route_name2**)
#		Placemark (name="Path") [data is here]

ns = {"kml":kml_default_namespace}
for item in input_root.findall("./kml:Document/kml:Folder/kml:Folder",ns):
	route_name = item.find("kml:name",ns).text
	print("Found a route: %s" %(route_name))
	
	# Get the Placemark (the real data)
	placemark = item.find("kml:Placemark",ns)
	
	# Set the placemark name correctly
	placemark_name = placemark.find("kml:name",ns)
	placemark_name.text = route_name
	
	# Remove style data that gpsbabel adds in
	placemark.remove(placemark.find("kml:styleUrl",ns))
	
	# Append the actual route data onto the output
	routes_folder.append(placemark)
	
print("\nXML output:")
print(etree.tostring(output_root, pretty_print=True, encoding='unicode'))

etree.ElementTree(output_root).write("fixedupkml.kml", xml_declaration=True, encoding='UTF-8', pretty_print=True)
